### ISSUE TITLE
Translate subcategories names and other main texts

### ISSUE THREAD

**Issue by smellai** [arduino/reference-de#1]
- Arduino Reference
- The Arduino programming language Reference, organized into Functions, Variable and Constant, and Structure keywords.
- functions
- For controlling the Arduino board and performing computations.
- Digital I/O
- Analog I/O
- Zero, Due & MKR Family
- Advanced I/O
- Time
- Math
- Trigonometry
- Characters
- Random Numbers
- Bits and Bytes
- External Interrupts
- Interrupts
- Communication
- Serial
- Stream
- USB
- Keyboard
- Mouse
- variables
- Arduino data types and constants.
- Constants
- Conversion
- Data Types
- Variable Scope & Qualifiers
- Utilities
- structure
- The elements of Arduino (C++) code.
- Sketch
- Control Structure
- Further Syntax
- Arithmetic Operators
- Comparison Operators
- Boolean Operators
- Pointer Access Operators
- Bitwise Operators
- Compound Operators

**Comment by kenan-kajkus** [comment]
Into which language should be translated

**Comment by kenan-kajkus** [comment]
so this should be translated bit after bit? I would like to contribute. To do so I need to fork it and then send pull-requests?

**Comment by per1234** [comment]
Generally that's correct but I believe the purpose of this particular issue is to request translation of words that need to be translated but are not part of the content of this repository. So for the list above you can just comment here with the translation of the list.

I believe that is also the case with issue https://github.com/arduino/reference-de/issues/3.

Thanks for your help!

**Comment by SeppPenner** [comment]
- Arduino Reference: Arduino-Referenz
- The Arduino programming language Reference, organized into Functions, Variable and Constant, and Structure keywords.: Die Arduino-Programmiersprachen-Referenz, unterteilt in Funktionen, Variablen und Konstanten, und Strukturen.
- functions: Funktionen
- For controlling the Arduino board and performing computations.: Zum kontrollieren des Arduino-Boards und zur Berechnung
- Digital I/O: Digitale Ein-/Ausgabe (Digital I/O is also quite common in German)
- Analog I/O: Analoge Ein/-Ausgabe Analog I/O is also quite common in German)
- Zero, Due & MKR Family: Zero-, Due-, MKR-Familie
- Advanced I/O: I would not translate that... **Fortgeschrittene Ein/-Ausgabe** does not sound good in German and for me is irritating as well
- Time: Zeit
- Math: Mathematik
- Trigonometry: Trigonometrie
- Characters: Zeichen
- Random Numbers: Zufallszahlen
- Bits and Bytes: Bits und Bytes
- External Interrupts: Externe Interrupts
- Interrupts: No translation, is the same in German, **Unterbrechungen** is wrong and sounds bad
- Communication: Kommunikation
- Serial: Seriell
- Stream: No translation, is the same in German
- USB: No translation, except you want to write **Universeller serialer Bus** which is the translation for **universal serial bus**
- Keyboard: No translation, is the same in German
- Mouse: Computermaus
- variables: Variablen
- Arduino data types and constants.: Arduino-Datentypen und -konstanten.
- Constants: Konstanten
- Conversion: Umwandlung/ Umrechnung
- Data Types: Datentypen
- Variable Scope & Qualifiers: Variablenscope und Bezeichner
- Utilities: Hilfsmittel
- structure: Struktur
- The elements of Arduino (C++) code.: Die Elemente der Arduino (C++) Programmiersprache
- Sketch: No translation, is the same in German
- Control Structure: Kontrollstruktur
- Further Syntax: Weitere Syntax
- Arithmetic Operators: Arithmetische Operatoren
- Comparison Operators: Vergleichsoperatoren
- Boolean Operators: Boolsche Operatoren
- Pointer Access Operators: Zeiger-Operatoren
- Bitwise Operators: Bitweise Operatoren
- Compound Operators: Verbundoperatoren (Don't know what compound operators are in this context...)

**Comment by SeppPenner** [comment]
In general, it's not so easy to translate things word by word from English to German. Sometimes, the sentences depend on the context, sometimes German just took the English words as well... :D

**Comment by smellai** [comment]
What are these dashes (-)? 

> Digital I/O: Digitale Ein-/Ausgabe (Digital I/O is also quite common in German)
Analog I/O: Analoge Ein/-Ausgabe Analog I/O is also quite common in German)
Zero, Due & MKR Family: Zero-, Due-, MKR-Familie

**Comment by SeppPenner** [comment]
These dashes mean either one or another. That's usually how you seperate options in German when using dashes (At least as far as I know, I'm not a linguist actually)...

Oh, I found a mistake I made: 

> Analog I/O: Analoge Ein/-Ausgabe Analog I/O is also quite common in German)

should be:

Analog I/O: Analoge Ein-/Ausgabe Analog I/O is also quite common in German)

To make it more clear:

Eingabe/Ausgabe is the same as Input/Output, if you shorten it in German, you can write Ein-/Ausgabe, too (Everyone then knows, that the word stem is the same).

Same example for Zero, Due & MKR Family: Zero-, Due- und MKR-Familie, here the log form would be Zero-Familie, Due-Familie und MKR-Familie.

**Comment by smellai** [comment]
Here you are
https://www.arduino.cc/reference/de/

**Comment by SeppPenner** [comment]
Nice, thank you :) I think I've made some mistakes yesterday, however: https://www.arduino.cc/reference/de/language/functions/advanced-io/pulsein/ 

I updated the links in the section (The were working for the github repo but not for the Arduino reference now...) I will need to update this later. 

Just take a look at the links, e.g. for HIGH on the reference page linked above:

![grafik](https://user-images.githubusercontent.com/9639361/41964728-16ccf7f2-79fb-11e8-9e4a-1c664a49b559.png)

**Comment by SeppPenner** [comment]
I agree. I updated this yesterday because the links didn't work within the github repository when I tested them :D Now they do not work on the page because the naming there is different. Nevermind, I can have a look at my last 5 commits or so and roll this back. Not a big deal.
