### ISSUE TITLE
Rendered German example reference shows 403 error

### ISSUE THREAD

**Issue by SeppPenner** [arduino/reference-de#13]
Just one question: The rendered Arduino reference template for entities is not avaiable in German, is it? https://www.arduino.cc/reference/en/asciidoc_sample/reference_terms/asciidoc_template-parent_of_entities/

When changing the link to https://www.arduino.cc/reference/de/asciidoc_sample/reference_terms/asciidoc_template-parent_of_entities/ there is a 403 error.

Can I solve that somehow or should I leave the English version in the readme links?

**Comment by smellai** [comment]
Let's keep the "/de" version and it will work as soon as I update the engine to support german, thanks!

**Comment by SeppPenner** [comment]
Ok, I guess, I will need to update some links in the readme as I missed to change all of them^^

**Comment by smellai** [comment]
It's available now, you just need to translate it too if you want
https://github.com/arduino/reference-de/tree/master/AsciiDoc_sample/Reference_Terms

**Comment by SeppPenner** [comment]
@smellai I have seen that. I will do when there is time. I planned to translate the functions folder first.
