### ISSUE TITLE
Translate Readme

### ISSUE THREAD

**Issue by smellai** [arduino/reference-de#2]

**Comment by SeppPenner** [comment]
Hi @smellai: I will try to provide you a PR soon on this^^ German is my mother language and I'm trying to help here.

**Comment by SeppPenner** [comment]
@smellai PR is there. I hope, i got the format correctly again :smirk:

https://github.com/arduino/reference-de/pull/10

**Comment by smellai** [comment]
we can give you write permissions so you can push translations directly

**Comment by SeppPenner** [comment]
@smellai Yeah, you can do that if you like. I will translate the different files step by step whenever I feel like I have the time to do so ;)
