### ISSUE TITLE
German Arduino reference page seems to be not updated for ages

### ISSUE THREAD

**Issue by SeppPenner** [arduino/reference-de#242]
I think the page under https://www.arduino.cc/reference/de/ is not updated for a long time. I already translated a lot of stuff but the changes are not shown. Could you check this, please? @smellai @mastrolinux

**Comment by smellai** [comment]
@SeppPenner the reference should be updated now, @rsora maybe we need to find a long term solution, this issue could happen again, there was an issue with the links scraper

**Comment by SeppPenner** [comment]
@smellai It looks better now. Just one more question: Why are the functions not shown correctly in the pverview page?

![image](https://user-images.githubusercontent.com/9639361/56288311-cb588500-611e-11e9-9ae1-f64a7f44c1fe.png)

If you compare the pages: https://www.arduino.cc/reference/de/ and https://www.arduino.cc/reference/en/, you will see that the English version contains all functions but the German version doesn't.

**Comment by smellai** [comment]
They will appear once translated!

**Comment by SeppPenner** [comment]
I thought that, too. The only things that are not yet translated, are the `Variables/Data Types` and `Functions/Communication` folders. The rest is already finished and should be visible...

**Comment by smellai** [comment]
Ah sorry! you need to translate subcategory metadata
https://github.com/arduino/reference-de/commit/256eeecc37384bae069f2fe4110cf46baaacc0ee

**Comment by SeppPenner** [comment]
Ah okay. I thought, I need to leave these as they are because the parser cannot read it otherwise. Thank you for the information.
