### ISSUE TITLE
Fix translation of side text

### ISSUE THREAD

**Issue by SeppPenner** [arduino/reference-de#252]
![image](https://user-images.githubusercontent.com/9639361/56571447-41e10100-65bd-11e9-91c0-6436d0710788.png)

In German, the spelling `diese Tutorial` does not make sense.

**Comment by SeppPenner** [comment]
Summing it up:

`Zweifel, wie man Github benutzt? Erfahre hier alles, was du wissen musst diese Tutorial` should be:

`Zweifel, wie man Github benutzt? Erfahre in diesem Tutorial alles, was du wissen musst.`

**Comment by smellai** [comment]
Fixed
