### ISSUE TITLE
undefined is shown in interrupts, noInterrupts has two see also sections

### ISSUE THREAD

**Issue by SeppPenner** [arduino/reference-de#259]
https://www.arduino.cc/reference/de/language/functions/interrupts/interrupts/

![grafik](https://user-images.githubusercontent.com/9639361/56868855-56c3f700-69f8-11e9-9b98-f16521e124b6.png)

https://www.arduino.cc/reference/de/language/functions/interrupts/nointerrupts/

![grafik](https://user-images.githubusercontent.com/9639361/56868865-765b1f80-69f8-11e9-935e-56339a4d9f9f.png)

**Comment by SeppPenner** [comment]
Not yet fixed...

**Comment by SeppPenner** [comment]
@per1234 Sorry to bother you again, but do you see the issue here? In the VSCode-Preview, it's rendered correctly for both...

![grafik](https://user-images.githubusercontent.com/9639361/57182083-8c0a9200-6e9b-11e9-99a5-4b535e12036e.png)

**Comment by per1234** [comment]
Your change looks good to me. I did similar fixes in https://github.com/arduino/reference-en/pull/488. I notice the Drone build failed (https://drone.arduino.cc/arduino/reference-de/366/3), but I don't know enough to say why it failed. Perhaps there was just a momentary glitch which caused the publishing of the updated content to fail, so your fix isn't showing up in the reference pages on arduino.cc.

**Comment by SeppPenner** [comment]
There is a lot of failed builds somehow. I do not see an issue either. I will open a several issue for this.

**Comment by SeppPenner** [comment]
Still not resolved.

**Comment by SeppPenner** [comment]
@smellai Thanks, I was missing this.
