### ISSUE TITLE
Wrong code formatting and cursive serial in all serials

### ISSUE THREAD

**Issue by SeppPenner** [arduino/reference-de#262]
https://www.arduino.cc/reference/de/language/functions/communication/serial/begin/

![grafik](https://user-images.githubusercontent.com/9639361/56868902-0d27dc00-69f9-11e9-844e-f0a320e4b51f.png)

![grafik](https://user-images.githubusercontent.com/9639361/56868911-2af54100-69f9-11e9-9c2b-c4fc862cf064.png)

**Comment by SeppPenner** [comment]
@per1234 Just one question: Is this intended or is it a `feature`?

**Comment by per1234** [comment]
It's intended. The idea is to indicate that _`Serial`_ stands for a Serial object. That could be `Serial`, `SerialUSB`, `Serial1`, `Serial2`, or `Serial3`. I followed the precedent of some existing documentation in using italics for this purpose, though I don't remember exactly which it was offhand. Perhaps there is some better way to communicate this information.

Reference: https://github.com/arduino/reference-en/pull/480

**Comment by SeppPenner** [comment]
Thank you, I will adjust this.
