### ISSUE TITLE
Fix wrong code formatting in long and unsignedInt

### ISSUE THREAD

**Issue by SeppPenner** [arduino/reference-de#269]
![grafik](https://user-images.githubusercontent.com/9639361/56869072-a7891f00-69fb-11e9-933e-65975da5ecb3.png)

https://www.arduino.cc/reference/de/language/variables/data-types/long/

**Comment by SeppPenner** [comment]
https://www.arduino.cc/reference/de/language/variables/data-types/unsignedint/

**Comment by per1234** [comment]
Fixed by https://github.com/arduino/reference-de/pull/286

**Comment by SeppPenner** [comment]
That's correct @per1234.
