### ISSUE TITLE
Wrong example codes in block comments

### ISSUE THREAD

**Issue by SeppPenner** [arduino/reference-de#272]
![grafik](https://user-images.githubusercontent.com/9639361/56869139-e9ff2b80-69fc-11e9-8f0f-87e17a0e30ad.png)

https://www.arduino.cc/reference/de/language/structure/further-syntax/blockcomment/

**Comment by per1234** [comment]
That is actually intentionally wrong. It's demonstrating this issue of using block comments inside of block comments. It jumped out at me while I was doing my review of the German Language Reference pages and it took me a few seconds to realize what was going on there.

**Comment by SeppPenner** [comment]
Ah, thanks. That was something I did not realize... However, I will keep this issue open as the translation inside the comment is not exactly what I would translate it now. I will try to change this soon.

**Comment by SeppPenner** [comment]
Ok, no. There's the new issue: https://github.com/arduino/reference-de/issues/291
