### ISSUE TITLE
Proof-read after all changes again.

### ISSUE THREAD

**Issue by SeppPenner** [arduino/reference-de#275]
After all issues are fixed, I need to proof-read again.

**Comment by SeppPenner** [comment]
@per1234 If you have some time, you could also check if there are some improvements possible. Thank you already ;)

**Comment by per1234** [comment]
Unfortunately, I don't have any knowledge of the German language. What I would suggest is that you post a request on the Deutsch section of the Arduino forum. It seems like a very active community there and I think there is a very good chance someone would be willing to help out.
https://forum.arduino.cc/index.php?board=31.0

**Comment by SeppPenner** [comment]
@per1234 I did not mean to proof-read the German stuff, just the formatting and so on. I've seen a lot mistakes yesterday and fixed already some. Probably, I will need to use another editor (VS Code with the ASCIIDoc plugin instead of Notepad++).

**Comment by per1234** [comment]
OK. I'll look it over for formatting issues later today.

I also have have been disappointed in my experiences with Notepad++ and ASCIIDoc, though I haven't spent a lot of time investigating whether it can be improved.

**Comment by SeppPenner** [comment]
> OK. I'll look it over for formatting issues later today.

Thank you really much already 👍 

> I also have have been disappointed in my experiences with Notepad++ and ASCIIDoc, though I haven't spent a lot of time investigating whether it can be improved.

Maybe there is a plugin as well, I have not searched yet.

**Comment by per1234** [comment]
I did a quick check over all the pages of the German version of the Arduino Language Reference and submitted pull requests for the small issues I found. It's looking very good!

I did notice one other thing, which I know you are not able to fix: there is some unnecessary line wrapping in the Verbundoperatoren section:

![german](https://user-images.githubusercontent.com/8572152/57123146-a0347f00-6d35-11e9-96f0-5ec4fe140c05.png)

---

Here's how it looks on the English version:

![english](https://user-images.githubusercontent.com/8572152/57123157-aa567d80-6d35-11e9-9760-aa25c48eb302.png)

---
I find the line wrapping makes that section much harder to read and there is plenty of horizontal space for it to not be wrapped.

**Comment by SeppPenner** [comment]
> I did a quick check over all the pages of the German version of the Arduino Language Reference and submitted pull requests for the small issues I found. It's looking very good!

I've already merged your changes. Thank you for your time 👍 

> I did notice one other thing, which I know you are not able to fix: there is some unnecessary line wrapping in the Verbundoperatoren section.
> I find the line wrapping makes that section much harder to read and there is plenty of horizontal space for it to not be wrapped.

I totally agree on that. I will check if there is a possibility to change this but for now the translation itself seems to be completely correct (Its just longer than in English). This is something @smellai or someone else needs to check as well.

**Comment by SeppPenner** [comment]
Depending on https://github.com/arduino/reference-de/issues/296, I will check everything after this issue is solved again.

**Comment by SeppPenner** [comment]
Todo: Check https://github.com/arduino/reference-de/issues/259 again.

**Comment by SeppPenner** [comment]
@SeppPenner https://github.com/arduino/reference-de/issues/259 is fixed now, do a re-check.

**Comment by SeppPenner** [comment]
Is already in work.
