### ISSUE TITLE
digitalRead() (marginal)

### ISSUE THREAD

**Issue by CombiesGit** [arduino/reference-de#277]
Schön, dass du(ihr?) dir die Arbeit gemacht hast!
Fein!

Habe erst überflogen....
Sieht alles in allem recht stimmig aus.

----
[https://www.arduino.cc/reference/de/language/functions/digital-io/digitalread/]
[](https://www.arduino.cc/reference/de/language/functions/digital-io/digitalread/)

> pin: Die Nummer des Digitalpins, die gelesen werden soll.

evtl. besser:
> pin: Die Nummer des Digitalpins, der (oder: welcher) gelesen werden soll.

```
int ledPin = 13; // LED verbunden auf Digitalpin 13
int inPin = 7;   // Button verbunden auf Digitalpin 7
int val = 0;     // Variable, um den gelesenen Wert zu speichern
```
Hier sollte vielleicht das "auf" in ein "mit" verwandelt werden

Dann, was mich allerdings auch im englischen Teil stört......
Und ich eigentlich lieber so sehen würde:
```
const byte ledPin = 13;    // LED verbunden mit Digitalpin 13
const byte inPin  =  7;    // Button verbunden mit Digitalpin 7
bool  val         =  true; // Variable, um den gelesenen Wert zu speichern
```
Naja...
Ist vielleicht etwas überzogen, die Erwartung.

**Comment by SeppPenner** [comment]
Hi, werde ich mir noch genauer anschauen. Ich war gestern auch beim Drüberlesen nicht ganz zufrieden mit einigen Formatierungsgeschichten und Formulierungen. (Sieht man vermutlich an den aktuell doch recht vielen Issues :D)
