### ISSUE TITLE
Übersetzung des Lib-Namen Wire 

### ISSUE THREAD

**Issue by wapjoe** [arduino/reference-de#279]
Hi,
der in https://www.arduino.cc/reference/de/language/functions/communication/stream/ übersetzte Bibliothekennamen Wire in Draht ist etwas unglücklich und sollte im Original bleiben. ;)
![Arduino-Referenz](https://user-images.githubusercontent.com/24509200/56907950-a0b6e680-6aa5-11e9-8742-7e9c6ba1d902.png)

Gruß
wapjoe

**Comment by SeppPenner** [comment]
Ja, damit hast du recht. Passiert, wenn man zu viele Sachen hintereinander übersetzt :/
