### ISSUE TITLE
Drone builds are failing with `level=fatal msg="Error: unable to trigger build for bcmi-labs/reference.`

### ISSUE THREAD

**Issue by SeppPenner** [arduino/reference-de#296]
If you take a look at https://drone.arduino.cc/arduino/reference-de, you can see that a lot of builds have failed with the error:

```bash
Warning: "fork: false" will be deprecated in future
         set "fork: true" to disable this warning
time="2019-05-03T20:02:50Z" level=fatal msg="Error: unable to trigger build for bcmi-labs/reference.\n"
```

What's the problem here and how can we fix the not correctly built stuff?

**Comment by mastrolinux** [comment]
I partially fixed it couple days ago. If there are other builds running at the same time our service crashes. We will add more capacity later on during this quarter.

**Comment by SeppPenner** [comment]
@mastrolinux Ah okay. But there is one thing I do not understand: Why doesn't drone get the correct stuff for failed builds if another build afterwards runs successfully? E.g. drone build 366 failed but 375 is finsihed successfully. Doesn't drone simply pull all changes from Git and update everthing?

The issue https://github.com/arduino/reference-de/issues/259 is already fixed but still incorrectly shown on the reference page.
