### ISSUE TITLE
Wrong Cross Link to Github

### ISSUE THREAD

**Issue by volvodani** [arduino/reference-de#297]
The link in this screen behind "Über GitHub kannst du Korrekturen und neue Dokumentation vorschlagen." has the wrong adress. The destination is the english git not the german.
Greetings
DerDani

**Comment by SeppPenner** [comment]
@smellai Can you change this, please. Thank you.

![image](https://user-images.githubusercontent.com/9639361/57284202-f9434080-70b0-11e9-86c6-104609704f85.png)

leads to https://github.com/arduino/reference-en instead of https://github.com/arduino/reference-de.

**Comment by SeppPenner** [comment]
@smellai Did you close this because new issues should first be discussed in the English version of the reference?

**Comment by smellai** [comment]
No, it should be fixed now

**Comment by SeppPenner** [comment]
It isn't... Check it out, please: https://www.arduino.cc/reference/de/

**Comment by smellai** [comment]
try in incognito or flush cache

**Comment by SeppPenner** [comment]
> try in incognito or flush cache

Yeah, caching issue. Is resolved now. Thank you.
