### ISSUE TITLE
Translate site texts

### ISSUE THREAD

**Issue by smellai** [arduino/reference-de#3]
- id: pageTitle
  translation: Language Reference

- id: pageDescription
  translation: "Arduino programming language can be divided in three main parts: structure, values (variables and constants), and functions."

- id: language
  translation: Language

- id: functions
  translation: functions

- id: variables
  translation: variables

- id: structure
  translation: structure

- id: libraries
  translation: Libraries

- id: glossary
  translation: Glossary

- id: editButton
  translation: Edit This Page

- id: license
  translation: "The Arduino Reference text is licensed under a <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" target=\"_blank\" rel=\"noopener\">Creative Commons Attribution-Share Alike 3.0 License</a>."

- id: githubLink
  translation: "Find anything that can be improved? <a href=\"https://github.com/arduino/reference-en\" target=\"_blank\" rel=\"noopener\">Suggest corrections and new documentation via GitHub.</a>"

- id: tutorialLink
  translation: "Doubts on how to use Github? Learn everything you need to know in <a href=\"https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37\" target=\"_blank\" rel=\"noopener\">this tutorial</a>."

**Comment by SeppPenner** [comment]
- id: pageTitle
  translation: Sprach-Referenz

- id: pageDescription
  translation: "Die Programmiersprache von Arduino kann in drei Hauptteile unterteilt werden: Struktur, Werte (Variablen und Konstanten) und Funktionen."

- id: language
  translation: Sprache

- id: functions
  translation: Funktionen

- id: variables
  translation: Variablen

- id: structure
  translation: Struktur

- id: libraries
  translation: Bibliotheken

- id: glossary
  translation: Glossar

- id: editButton
  translation: Bearbeite diese Seite

- id: license
  translation: "Der Arduino-Referenztext ist lizenziert unter der <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" target=\"_blank\" rel=\"noopener\">Creative Commons Attribution-Share Alike 3.0 Lizenz</a>."

- id: githubLink
  translation: "Findest du etwas, das verbessert werden kann? <a href=\"https://github.com/arduino/reference-de\" target=\"_blank\" rel=\"noopener\">Über GitHub kannst du Korrekturen und neue Dokumentation vorschlagen.</a>"

- id: tutorialLink
  translation: "Zweifel, wie man Github benutzt? Erfahre hier alles, was du wissen musst<a href=\"https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37\" target=\"_blank\" rel=\"noopener\">this tutorial</a>."

**Comment by smellai** [comment]
Thanks @SeppPenner , I traslated the texts, let's wait for the automatic deploy to be fixed to see the changes https://github.com/arduino/reference-de/issues/242
