### ISSUE TITLE
Undefined is shown on stream main page.

### ISSUE THREAD

**Issue by SeppPenner** [arduino/reference-de#314]
https://www.arduino.cc/reference/de/language/functions/communication/stream/

![grafik](https://user-images.githubusercontent.com/9639361/58386164-e959b500-7ffb-11e9-8baa-0d438fc73d7e.png)

**Comment by SeppPenner** [comment]
@smellai I do not see the issue here. Can you check this, please?

**Comment by per1234** [comment]
@SeppPenner here's the fix: https://github.com/arduino/reference-en/pull/603

I prefer to fix the problems that occur also in the reference-en repository there first and then push that fix out to all the translation repositories from there after it's merged. If we only fix a global issue locally in a single translation repository then none of the other repositories benefit from that fix and the fix may even end up being reverted accidentally later during a sync from reference-en.

**Comment by SeppPenner** [comment]
@per1234 Ah, it really was the missing see also section. That's what I assumed yesterday but I wasn't sure.

>I prefer to fix the problems that occur also in the reference-en repository there first and then push that fix out to all the translation repositories from there after it's merged.

I totally agree with that. Honestly, I didn't check this in the English version this time 😟
