### ISSUE TITLE
translate leftover paragraph in de:loop()

### ISSUE THREAD

**Issue by 1100101111** [arduino/reference-de#412]
translate first paragraph in loop() [https://github.com/arduino/reference-de/blob/master/Language/Structure/Sketch/loop.adoc](url)

Seems like "Beschreibung" got left behind :)

https://www.arduino.cc/reference/de/language/structure/sketch/loop/

pull request: #413 

(sorry, finding my way in GitHub)

**Comment by 1100101111** [comment]
#413

**Comment by SeppPenner** [comment]
This is merged now :)
