### ISSUE TITLE
Add repository title to github description section.

### ISSUE THREAD

**Issue by SeppPenner** [arduino/reference-de#56]
Hi @smellai: Could you add the description below to the github description section, please?

**Die deutsche Version der Arduino-Dokumentation**

![image](https://user-images.githubusercontent.com/9639361/42084227-5fbd10e4-7b8d-11e8-8211-131342a7b234.png)

**Comment by mastrolinux** [comment]
Done, also added the link to the online doc

**Comment by SeppPenner** [comment]
Thanks :+1:
